#!/bin/bash
#
# Remove a plugin and its submodule
# Usage: purge-bundle name 

if [ ! -n "$1"  ]
then
    echo "Usage: `basename $0` name"
    exit 1;
fi  

git submodule deinit -f "$1"
git rm "$1"
git commit "$1" .gitmodules -m "Removed bundle: ""$1"
rm -rf .git/modules/bundle/"$1"

echo "Submodule "$1" deleted."
